### ISSUE TITLE
One Way Date Mask - Year Not Setting

### ISSUE THREAD

**Issue by jrock2004** [brandynbennett/ember-inputmask#98] opened 2019-04-05 13:47 UTC
I just updated to version `0.8.5` and having an issue with with always seeing YYYY instead of what I am typing

```
{{one-way-date-mask
  creditCard.expirationDateMasked
  id=el.id
  placeholder="MM/YYYY"
  class="expirationDate form-control"
  showMaskOnHover=false
  showMaskOnFocus=false
  options=(hash inputFormat="MM/YYYY" outputFormat="MM/YYYY")
  update=(action (mut creditCard.expirationDateMasked))}}
```

What I see in the input is `12/YYYY`

If below this code I put `{{creditCard.expirationDateMasked}}` I see `12/2025`What am I doing wrong?

**Update 1:**
I tried just doing the following and still same issue 

```
{{one-way-date-mask
  class="expirationDate form-control"
  options=(hash inputFormat="MM/YYYY")}}
```

I then type `12/2025` but all I see is `12/YYYY`

**Comment by brandynbennett** [comment] 2019-04-13 02:55
@jrock2004 sorry for the late response. The issue is that `YYYY` is not a valid mask for datetime mask  as defined in [here](https://github.com/RobinHerbots/Inputmask/blob/4.x/README_date.md). You have to make it `yyyy` instead.

Please let me know if that solves it for you and I'll close this.

**Comment by brandynbennett** [comment] 2019-04-13 02:56
`MM` also stands for minutes, so you'll want to lowercase that as well `mm/yyyy`

**Closed** 2020-05-30 01:36 UTC
Labels: question
